## Using https://github.com/arnp/herring-cove theme
#
name: Unité de Transplantation Hépatique
author: Jean-Baptiste Richardet
baseurl: /testJekyll
description: Hôpital Henri Mondor Créteil
email: contact[at]aphp.fr

##Make sure to edit the above fields, especially for disqus.


#highlighter: pygments
#markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
